### ISSUE TITLE
File encryption/decryption

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android-node#18]
I've done some research and found the file encryption/decryption is quite expensive :( 

Please look at attached images. For example, encryption/decryption of 5Mb takes a lot of memory. 
For 1Mb
![screenshot from 2018-12-18 14-29-15](https://user-images.githubusercontent.com/2863246/50154905-50e43980-02d3-11e9-91ef-7a624c292679.png)

For 5Mb
![screenshot from 2018-12-18 14-34-44](https://user-images.githubusercontent.com/2863246/50154908-517cd000-02d3-11e9-9dd4-cff534b58ab6.png)

**Comment by tomholub** [comment]
The `Native: 274.5` looks like amounts allocated over the lifetime? Do I understand it correctly?

In that case, for 5MB encryption/decryption it's showing `Native: 69.9 MB` peak memory usage.

It still seems like a lot. It will definitely be improved with streaming. How can I see the charts myself? Maybe I can optimize it.

**Comment by tomholub** [comment]
For node, accumulated amount allocated over time is not the best metric because it should be garbage collected as soon as it's not needed. But peak memory usage is very interesting.

**Comment by DenBond7** [comment]
> The Native: 274.5 looks like amounts allocated over the lifetime? Do I understand it correctly?

it's a peak memory usage. 

> How can I see the charts myself?

https://developer.android.com/studio/profile/memory-profiler

> For node, accumulated amount allocated over time is not the best metric because it should be garbage collected as soon as it's not needed. 

Yes. But it's still a lot of memory which the native code uses

**Comment by tomholub** [comment]
memory issues will be solved when we use streaming - it's on future roadmap
