### ISSUE TITLE
fix Node error handling in Java

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android-node#24]
Right now there will be a NullPonterException if there is an exception and Node does not respond. 

Instead the error should be encapsulated back into the results.

This used to work before the code was updated, and needs to be fixed.

It would look something like this:

```Java
try {
  RequestBody requestBody = new NodeRequestBody<>("encryptMsg", new Pubkeys(TestData.getMixedPubKeys()), data);
  Response<ResponseBody> responseBody = requestService.request(requestBody).execute();
  return new EncryptMsgResult(null, responseBody.body().byteStream(), responseBody.raw().receivedResponseAtMillis() - responseBody.raw().sentRequestAtMillis());
} catch (Exception e) {
  return new EncryptMsgResult(e, null, 0); // todo - get time
}
```

This would then be put into a request method. Related #23

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android-node/commit/29b5af32a511be1bfb9ba940a70c4ac253499021

**Comment by DenBond7** [comment]
#28
