### ISSUE TITLE
RawNodeResult architecture

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android-node#28]
I've explored in details RawNodeResult. And I've found some things which need to improve.

What a situation we have now: 

- RawNodeResult has an incoming input stream as a field. For short responses, I don't see big problems. But for file actions, it's a problem. Because by default, okhttp makes a buffer which keeps all received data in the memory. It's not good for the app performance. In that case, we can easily receive the out of memory exceptions.

- we do some actions in the UI thread(parsing, extracting). It's bad too.

What I propose:

1. The best variant for Android - it's work with already extracted data, which will be extracted in the background thread. When I return a result to the main thread I need to be sure that it's a simple data with simple methods (like getters: getVersion, getEncryptedData and etc.). I use such logic when I receive a simple response from some API (When we are working with json)

1. You told me we are working with the next schema: `Request is: "endpoint\njson\nbytes" and response is "json\nbytes"`.  For the big raw data after json, we don't need to use a buffer in the memory. If it will be a file encryption/decryption action I can just save an incoming input stream to a file without buffering it in the memory. Actually, It's what I need when I working with such operations. Then I work with Uri which refers to that file. It's a standard Android way.

1. I would like to separate result data from RawNodeResult. RawNodeResult should contain only logic of parsing incoming information (maybe we need to rename it, maybe something like NodeResultFactory) and produce only simple objects.

**Comment by tomholub** [comment]
Thanks for the comments
1. Doing all processing in background and only passing simple results sounds ok
2. Putting the result into a file sounds ok, especially if we want to process it all in bg then pass to fg. It would not make sense to pass it as a big object that takes up memory.
3. I would call it NodeResultParser

I would really like to keep it simple, and for this, I suggest that NodeResultParser should be very general with no specific logic for each call. So it would not have any JSON parsing. It would only strip the JSON line, then dump the data into a file. If there is no data after the json, it should not create a file and just pass json and a null. So the result would be:
1) `Exception error` (or null if there was no error)
2) `String jsonLine` (or null if there was error and we could not get a json line)
3) `Uri data` (or null if there was no data, or null if there was error)

You could now call this simple object `RawNodeResult` if you want.

Then you would have maybe `AbstractNodeResult` that can parse a Json and do other common things with all methods protected. Also this would have a public `Exception getErr()`. This method would internally save `wasErrorChecked=true`; Also there would be a `protected throwIfErrNotChecked()` method.

Finally you would have for example `EncryptMsgResult` and many others that extend `AbstractNodeResult`. The constructor would accept `RawNodeResult` and parse all details right in the constructor. Now you have a simple object that you can send to the main thread.

I think all public getters of `EncryptMsgResult` and similar should internally call `throwIfErrNotChecked();` before returning the value. This will ensure that we always have to check the error first before accessing data.

Let me know what you think about this design.

**Comment by DenBond7** [comment]
@tomholub 
> I suggest that NodeResultParser should be very general with no specific logic for each call. ... and just pass json and a null. .... You could now call this simple object RawNodeResult if you want.

Perfect! I realy like it.

> I think all public getters of EncryptMsgResult and similar should internally call throwIfErrNotChecked(); before returning the value. This will ensure that we always have to check the error first before accessing data.

Of course, we can do that. But I don't know is that really needed. I can explain why. For example, we have the next code:

```
public void onChange(AbstractNodeResult result){
        EncryptMsgResult msgResult = (EncryptMsgResult )result;

        if (msgResult.getErr != null) {
                 //handle error
        } else {
                //access data
               PgpBlock[] blocks = msgResult.getPgpBlocks();
               String encryptedText = msgResult.getEncryptedTExt();  
        }

}
```
In most cases (maybe in all) I will use only one point for the error checking. Before accessing data I need to be sure we don't have any errors(it is logical). I think `throwIfErrNotChecked ` is redundant.

**Comment by tomholub** [comment]
Ok. If you are confident that you will always check for errors first, then
we don't have to include this error check forcing mechanism. That will make
it a bit simpler, which is also good. I like simple.

**Comment by DenBond7** [comment]
Moved
